export const FETCH_COUNTRIES_BEGIN = "FETCH_COUNTRIES_BEGIN";
export const FETCH_COUNTRIES_ERROR = "FETCH_COUNTRIES_ERROR";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FILTER_SEARCH = "FILTER_SEARCH";
export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const TOGGLE_MODE = "TOGGLE_MODE";
export const UPDATE_PREV_PAGE = "UPDATE_PREV_PAGE";
